# Generated by Django 3.1.7 on 2021-03-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashtrayapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonsmoker',
            name='cigs_per_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nonsmoker',
            name='cigs_per_pack',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nonsmoker',
            name='price_per_pack',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='nonsmoker',
            name='quit_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='nonsmoker',
            name='start_smoking_year',
            field=models.DateField(null=True),
        ),
    ]
