# Generated by Django 3.1.7 on 2021-03-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashtrayapi', '0002_auto_20210309_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='redeemed',
            field=models.BooleanField(default=False),
        ),
    ]
